import { TUTORIAL, DAILY_QUESTS } from './constants';
import { dateKey, weekKey } from './formulas';
import { GameState } from './types';

export const createInitialState = (): GameState => ({
  appearance: 0,
  tutorialStep: 0,
  energy: 0,
  maxEnergy: 100,
  // Начальные ресурсы у всех пользователей равны 0
  bullets: 0,
  gold: 0,
  zhetons: 0,
  matches: 0,
  grenades: 0,
  medkits: 0,
  keys: 0,
  level: 1,
  baseStamina: 40,
  luck: 20,
  carLevel: 1,
  currentDistrict: 'southgate',
  unlockedDistricts: ['southgate'],
  weapon: {
    name: 'Ржавый пистолет',
    level: 0,
    broken: false,
    baseDamage: 6,
    upgraded: false,
  },
  equipmentIds: [],
  inventory: [],
  craftingRecipes: ['repair_kit', 'medkit_bundle'],
  clan: null,
  daily: {
    dateKey: dateKey(),
    lotteryUsed: false,
    goldClaimed: false,
    quests: DAILY_QUESTS.map((q) => ({
      questId: q.id,
      progress: 0,
      completed: false,
      claimed: false,
    })),
  },
  gast: {
    weekKey: weekKey(),
    active: false,
    districtId: null,
  },
  battle: null,
  raid: null,
  radioRequests: ['Сосед просит аптечку у стены', 'Клан ищет помощь на рынке'],
  lastMessage: TUTORIAL[0],
  soundEnabled: true,
  showMap: false,
  showBossModal: false,
  showRaidModal: false,
  activeRaid: null,
  mapRaids: [
    {
      id: 'raid_1',
      x: 25,
      y: 30,
      type: 'yellow',
      name: 'Заброшенный склад',
      description: 'Лёгкий рейд, 15 минут',
      energyCost: 10,
      rewards: {
        bullets: 8,
        matches: 12,
        materials: 5,
      },
      isRunning: false,
      completed: false,
    },
    {
      id: 'raid_2',
      x: 60,
      y: 45,
      type: 'red',
      name: 'Крепость мутантов',
      description: 'Опасный рейд, 30 минут',
      energyCost: 20,
      rewards: {
        bullets: 15,
        matches: 20,
        materials: 10,
      },
      isRunning: false,
      completed: false,
    },
    {
      id: 'raid_3',
      x: 40,
      y: 70,
      type: 'yellow',
      name: 'Полицейский участок',
      description: 'Средний рейд, 15 минут',
      energyCost: 15,
      rewards: {
        bullets: 10,
        matches: 15,
        materials: 8,
      },
      isRunning: false,
      completed: false,
    },
  ],
  currentLocation: 'location1',
});
